name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the project
        run: |
          echo "Building the project..."
          sleep 2  # Simulating build
          echo "Project built successfully!"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          sleep 2  # Simulating tests
          echo "Tests completed successfully!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to environment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "Deploying to development environment..."
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploying to production environment..."
          fi
